ALTER TABLE MY_FRIST_TABLE ADD COLUMN Is_active BOOLEAN DEFAULT TRUE;

ALTER TABLE MY_FRIST_TABLE MODIFY Name VARCHAR(140);

ALTER TABLE MY_FRIST_TABLE MODIFY COLUMN Gender ENUM('Male','Female','Other') AFTER Date_of_birth;

ALTER TABLE MY_FRIST_TABLE MODIFY COLUMN Email VARCHAR(150) FIRST;

