CREATE TABLE MY_FRIST_TABLE(
Id INT AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(100) NOT NULL,
Email VARCHAR(150) NOT NULL UNIQUE,
Gender ENUM('Male','Female','Other'),
Date_of_birth DATE,
Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
