-- PRIMARY KEY
CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100)
);

ALTER TABLE users DROP PRIMARY KEY;

ALTER TABLE users DROP INDEX email;

ALTER TABLE users AUTO_INCREMENT = 1000;
